# Generated by Django 3.0.5 on 2020-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=900)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=900)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
